name: C++ CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup C++ environment
      run: sudo apt-get install -y g++

    - name: Build project
      run: make build

    - name: Run AST tests
      run: make ast_test

    - name: Run Lexer tests
      run: make lexer_test

    - name: Run REPL tests
      run: make repl_test

    - name: Run Token tests
      run: make token_test
