name: C++ CI/CD

on:
  push:
    branches-ignore: [] # Runs on push to any branch
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup C++ environment
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build project
      run: make -C src/monkey build

    - name: Run Token tests
      run: make -C src/monkey token_test

    - name: Run Lexer tests
      run: make -C src/monkey lexer_test

    - name: Run AST tests
      run: make -C src/monkey ast_test

    - name: Run Parser tests
      run: make -C src/monkey parser_test

    - name: Run Object tests
      run: make -C src/monkey object_test

    - name: Run Evaluator tests
      run: make -C src/monkey evaluator_test

    - name: Run REPL tests
      run: make -C src/monkey repl_test

    - name: Run all tests
      run: make -C src/monkey tests

    # Add a deployment step
    - name: Deploy to PythonAnywhere
      if: success() # This ensures deployment runs only if all previous steps were successful
      uses: appleboy/ssh-action@master
      with:
        host: 'ssh.pythonanywhere.com'
        username: 'ag7432'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ag7432/yoxs/src/python_interface
          git pull
          source /home/ag7432/.virtualenvs/myvirtualenv/bin/activate
          # Add any additional commands needed for your deployment
