name: C++ CI/CD

on:
  push:
    branches-ignore: [] # Runs on push to any branch
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup C++ environment
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build project
      run: make -C src/monkey build

    - name: Run Token tests
      run: make -C src/monkey token_test

    - name: Run Lexer tests
      run: make -C src/monkey lexer_test

    - name: Run AST tests
      run: make -C src/monkey ast_test

    - name: Run Parser tests
      run: make -C src/monkey parser_test

    - name: Run Object tests
      run: make -C src/monkey object_test

    - name: Run Evaluator tests
      run: make -C src/monkey evaluator_test

    - name: Run REPL tests
      run: make -C src/monkey repl_test

    - name: Run all tests
      run: make -C src/monkey tests

  deploy-to-heroku:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      uses: akhileshns/heroku-deploy@v3.12.12 # This action allows deploying Docker containers as well
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "yoxs"
        heroku_email: "yams@nyu.edu"
        usedocker: true
